# Generated by Django 4.2.4 on 2023-08-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.BigIntegerField()),
                ('sats_level', models.IntegerField()),
                ('alert_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
