# Generated by Django 4.2.4 on 2023-08-27 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_device_id_useralert_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAlert',
            new_name='Alert',
        ),
        migrations.CreateModel(
            name='LastAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('last_alert', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alert')),
            ],
        ),
    ]
